name: 'Bundle size diff'
author: 'Nejc Zdovc'
description: 'Report webpack bundle size change in the PR'
inputs:
  base_path:
    description: 'Path to base stats file'
    required: true
  pr_path:
    description: 'Path to PR stats file'
    required: true
  excluded_assets:
    description: 'Regex that will exclude some assets'
    required: false
outputs:
  success:
    description: 'Reports back success, boolean as string'
  base_file_size:
    description: 'Bundle size of base branch that you are targeting in the PR in bytes'
  pr_file_size:
    description: 'Bundle size of PR branch in bytes'
  diff_file_size:
    description: 'Diff size of compared branches in bytes'
  percent:
    description: 'Diff size of compared presented in percentage'
  raw:
    description: 'Raw JSON output of the diff'
branding:
  icon: bar-chart-2
  color: orange
runs:
  using: 'node16'
  main: 'dist/index.js'
